// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfhqtsenykkfyavvmixt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmaHF0c2VueWtrZnlhdnZtaXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTA2NTIsImV4cCI6MjA3MTAyNjY1Mn0.BbFZ9wE3eVPedopRHedMXoKv7LNEH3CizvdW306JHC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});